#!/bin/bash


sed -i -r   -e 's/[ÂÁÃÀ]/A/g' -e 's/[âáãà]/a/g'      -e 's/[ÉÊẼ]/E/g'  -e 's/[éẽê]/e/g'     -e 's/[Í]/I/g'     -e 's/[í]/i/g'        -e 's/[ÓÕÔ]/O/g'  -e 's/[óõô]/o/g'       -e 's/[ú]/u/g'    -e 's/[Ú]/U/g'       -e 's/ç/c/g'    $1

